### ISSUE TITLE
`Staff tag` Option doesn't work

### ISSUE THREAD

**Issue by itzdrli** [darkpixlz/DarkPixlz-s-Modern-Theme#2]
like the title says, when i disabled the option Staff Tag option and saved, then i refreshed the page, but the staff tag is still there
![pic1](https://user-images.githubusercontent.com/52338732/221437579-e40db57d-fe35-4146-b269-4c1c9211fd24.png)
![pic2](https://user-images.githubusercontent.com/52338732/221437598-549a99b2-f8a6-45c3-a45f-c1f1a6293288.png)

**Comment by pyxfluff** [comment]
Thanks, will look at it.

**Comment by pyxfluff** [comment]
Fixed in latest commit

**Comment by itzdrli** [comment]
> Fixed in latest commit

still not working
![pic1](https://user-images.githubusercontent.com/52338732/222735994-da83e00c-ed15-46c9-acb7-9f1513a6591c.png)
![pic2](https://user-images.githubusercontent.com/52338732/222736085-993b9d1c-b12d-4435-bccf-b5212ffc6675.png)
Discourse version  3.1.0.beta2(827df072a6)
latest version of theme

**Comment by pyxfluff** [comment]
I see, this is because of a merge conflict last night and Git must have kept the live version, will fix.

**Comment by pyxfluff** [comment]
Fixed
